FROM centos:7

SHELL ["/bin/bash", "-c"]

WORKDIR /tmp

RUN yum -y install epel-release git make \
    gcc gcc-c++ gcc-gfortran \
    xerces-c-devel zlib-devel wget \
    openssl-devel bison flex boost-devel

# Modern compilers 
RUN yum -y install centos-release-scl && yum -y install devtoolset-7

# CMake (3.22.2 from source)
RUN wget https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2.tar.gz && \
    tar zxf cmake-3.22.2.tar.gz && \
    rm -rfv cmake-3.22.2.tar.gz && \
    cd cmake-3.22.2 && \
    ./bootstrap && \
    make install && \
    cd ../ && \
    rm -rfv cmake-3.22.2
    

# CLHEP
RUN wget https://proj-clhep.web.cern.ch/proj-clhep/dist1/clhep-2.4.5.1.tgz && \
    tar -xf clhep-2.4.5.1.tgz && rm -rf clhep-2.4.5.1.tgz && \
    source scl_source enable devtoolset-7 && \
    mkdir clhep-2.4.5.1-build && cd clhep-2.4.5.1-build && cmake ../2.4.5.1/CLHEP/ && \
    make -j6 && make install && cd ../ && rm -rfv 2.4.5.1 clhep-2.4.5.1-build

# X11 
RUN yum -y install xorg-x11-server-Xorg xorg-x11-xauth libX11-devel \
    libXpm-devel libXft-devel libXext-devel libXmu-devel 

# OpenGL (EGL GLX egl gl glu glx opengl xmesa)
RUN yum -y install freeglut-devel

# Python
RUN yum -y install python3-pip python3

# Qt5 
RUN yum -y install qt5-qtbase-devel 

# ROOT
RUN yum -y install root python36-root

# HEPMC3
RUN yum -y install HepMC3-rootIO-devel

# Geant4
RUN wget https://github.com/Geant4/geant4/archive/v10.7.3.tar.gz && \
    tar zxf v10.7.3.tar.gz && mkdir geant4-10.7.3-build && cd geant4-10.7.3-build && \
    source scl_source enable devtoolset-7 && \
    cmake ../geant4-10.7.3 -DGEANT4_INSTALL_DATA=ON -DGEANT4_USE_GDML=ON -DGEANT4_USE_OPENGL_X11=ON \
    -DGEANT4_USE_SYSTEM_CLHEP=ON -DGEANT4_USE_QT=ON -DGEANT4_USE_RAYTRACER_X11=ON && make -j6 && make install \
    && cd ../ && rm -rfv geant4-10.7.3-build geant4-10.7.3 v10.7.3.tar.gz && echo 'source /usr/local/bin/geant4.sh' >> ~/.bashrc

RUN dbus-uuidgen > /var/lib/dbus/machine-id && \
    mkdir -p /var/run/dbus && \
    dbus-daemon --config-file=/usr/share/dbus-1/system.conf --print-address

#RUN echo 'export LIBGL_ALWAYS_SOFTWARE=true' >> ~/.bashrc && \
RUN echo 'export QT_GRAPHICSSYSTEM="native"' >> ~/.bashrc