FROM centos:7

SHELL ["/bin/bash", "-c"]

WORKDIR /tmp

RUN yum -y install epel-release git make \
    gcc gcc-c++ gcc-gfortran \
    xerces-c-devel zlib-devel wget \
    openssl-devel bison flex boost-devel

# Modern compilers 
RUN yum -y install centos-release-scl && yum -y install devtoolset-9

# CMake (3.22.2 from source)
RUN wget https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2.tar.gz && \
    tar zxf cmake-3.22.2.tar.gz && \
    rm -rfv cmake-3.22.2.tar.gz && \
    cd cmake-3.22.2 && \
    ./bootstrap && \
    make -j10 install && \
    cd ../ && \
    rm -rfv cmake-3.22.2
    
# X11 
RUN yum -y install xorg-x11-server-Xorg xorg-x11-xauth libX11-devel \
    libXpm-devel libXft-devel libXext-devel libXmu-devel 

# OpenGL (EGL GLX egl gl glu glx opengl xmesa)
RUN yum -y install freeglut-devel

# Python
RUN yum -y install python3-pip python3

# Qt5 
RUN yum -y install qt5-qtbase-devel 

# HEPMC3
RUN yum -y install HepMC3-rootIO-devel

# turn on the useful compiler by default
RUN echo 'source scl_source enable devtoolset-9' >> ~/.bashrc
