
BASEDIR=`pwd`
#echo $BASEDIR
INSTALLDIR=$BASEDIR/install
SRCDIR=$BASEDIR/src
BUILDDIR=$BASEDIR/build
NCPU=20
#echo $INSTALLDIR
#echo $SRCDIR
#echo $BUILDDIR

export PATH=$INSTALLDIR/bin/:./:$PATH
export LD_LIBRARY_PATH=$INSTALLDIR/lib/
export PYTHONPATH=$INSTALLDIR/lib/