/* 
Beam Delivery Simulation (BDSIM) Copyright (C) Royal Holloway, 
University of London 2001 - 2024.

This file is part of BDSIM.

BDSIM is free software: you can redistribute it and/or modify 
it under the terms of the GNU General Public License as published 
by the Free Software Foundation version 3 of the License.

BDSIM is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with BDSIM.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef BDSPHOTONCOUNTER_H
#define BDSPHOTONCOUNTER_H 

#include "G4Track.hh"

/**
 * @brief A class for counting the number of photons generated by scintillators.
 *
 * @author L. Deacon
 * 
 */

class BDSPhotonCounter 
{
public:
  static BDSPhotonCounter* Instance();
  ~BDSPhotonCounter();
  
  void countPhoton(const G4Track* aTrack);
  G4double nPhotons() const;
  G4double energy() const;

private:
  BDSPhotonCounter();
  G4double _nPhotons;
  G4double _energy;
  static BDSPhotonCounter* _instance;

};

inline G4double BDSPhotonCounter::nPhotons() const{
  return _nPhotons;
}

inline G4double BDSPhotonCounter::energy() const{
  return _energy;
}

#endif

