PYMADX = ./pymadx/
PYMAD8 = ./pymad8/
PYTRANSPORT = ./pytransport/
PYBDSIM = ./pybdsim/

all:
	$(MAKE) develop -C PYBDSIM
	$(MAKE) develop -C PYMADX
	$(MAKE) develop -C PYMAD8
	$(MAKE) develop -C PYTRANSPORT

.DEFAULT_GOAL := all
