/* 
Beam Delivery Simulation (BDSIM) Copyright (C) Royal Holloway, 
University of London 2001 - 2019.

This file is part of BDSIM.

BDSIM is free software: you can redistribute it and/or modify 
it under the terms of the GNU General Public License as published 
by the Free Software Foundation version 3 of the License.

BDSIM is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with BDSIM.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifdef USE_HEPMC3

#ifndef BDSHEPMC3READER_H
#define BDSHEPMC3READER_H

#include "BDSEventGeneratorFileType.hh"

#include "globals.hh"
#include "G4ThreeVector.hh"
#include "G4VPrimaryGenerator.hh"

class BDSBunch;
class G4Event;

namespace HepMC3
{
  class GenEvent;
  class Reader;
}

/**
 * @brief Loader to use any HepMC3 compatible file.
 * 
 * Interface to use HepMC3 library to load a variety of files.
 * 
 * This is largely based on Geant4's example
 * examples/extended/eventgenerator/HepMC/HepMCEx01, however it
 * has been rewritten to use HepMC3 library rather than HepMC2.
 * Additionally, the interface has been written based on HepMC3
 * example "convert_example" to use multiple reader classes.
 * 
 * @author Helena Pikhartova, Laurie Nevay
 */

class BDSHepMC3Reader: public G4VPrimaryGenerator
{
public:
  /// Constructor takes full distrType string including semicolon and
  /// eventgeneratorfile prefix. The filename is assumed to be correctly
  /// prefixed if a relatie path already. The bunch definition is used
  /// for the reference coordinates and offset of the beam point.
  BDSHepMC3Reader(const G4String& distrType,
		  const G4String& fileNameIn,
		  BDSBunch*       bunchIn);
  virtual ~BDSHepMC3Reader();

  /// Accessor.
  inline HepMC3::GenEvent* GetHepMCGenEvent() const {return hepmcEvent;}

  // The default behavior is that a single HepMC event generated by
  // GenerateHepMCEvent() will be converted to G4Event through HepMC2G4().
  virtual void GeneratePrimaryVertex(G4Event* anEvent);

  /// Advance to the correct event number in the file for recreation.
  virtual void RecreateAdvanceToEvent(G4int eventOffset);

protected:
  /// Construct the member "reader" and open the file for reading.
  void OpenFile();

  /// Close and delete reader. Have to delete as HepMC3 readers have no iteration
  /// or ability to loop back to the beginning.
  void CloseFile();

  /// Clear the hepmcEvent object, reallocate and read a single event and fill that member.
  void ReadSingleEvent();

  /// Conversion from HepMC::GenEvent to G4Event.
  void HepMC2G4(const HepMC3::GenEvent* hepmcevt, G4Event* g4event);

  
  // We  have to take care for the position of primaries because
  // primary vertices outside the world voulme give rise to G4Execption.
  // If the default implementation is not adequate, an alternative
  // can be implemented in your own class.
  virtual G4bool CheckVertexInsideWorld(const G4ThreeVector& pos) const;
  
  // Note that the life of HepMC event object must be handled by users.
  // In the default implementation, a current HepMC event will be
  // deleted at GeneratePrimaryVertex() in the next event.
  HepMC3::GenEvent* hepmcEvent; // (care for single event case only)

private:
  /// Do not require default constructor.
  BDSHepMC3Reader() = delete;

  HepMC3::Reader* reader;
  G4String        fileName;
  BDSBunch*       bunch;
  BDSEventGeneratorFileType fileType;
};

#endif
#endif
