if (USE_AFS AND NOT CLHEP_LIBRARY_DIR)
   if (APPLE)
      set(CLHEP_INCLUDE_DIR /afs/cern.ch/sw/lcg/external/clhep/2.1.0.1/x86_64-mac106-gcc42-opt/include)
      set(CLHEP_LIBRARY_DIR  /afs/cern.ch/sw/lcg/external/clhep/2.1.0.1/x86_64-mac106-gcc42-opt/lib)
   elseif (RHL6)
      if (GCC_VERSION VERSION_GREATER 4.7 OR GCC_VERSION VERSION_EQUAL 4.7)
         set(CLHEP_INCLUDE_DIR /afs/cern.ch/sw/lcg/external/clhep/2.1.4.1/x86_64-slc6-gcc47-opt/include)
         set(CLHEP_LIBRARY_DIR  /afs/cern.ch/sw/lcg/external/clhep/2.1.4.1/x86_64-slc6-gcc47-opt/lib)
      else()
         set(CLHEP_INCLUDE_DIR /afs/cern.ch/sw/lcg/external/clhep/2.1.4.1/x86_64-slc6-gcc46-opt/include)
         set(CLHEP_LIBRARY_DIR  /afs/cern.ch/sw/lcg/external/clhep/2.1.4.1/x86_64-slc6-gcc46-opt/lib)
      endif()
   endif()
else()
   if($ENV{VERBOSE})
      set(CLHEP_CONFIG_DEBUG TRUE)
   endif()
   find_package(CLHEP REQUIRED)
   message(STATUS "Looking for CLHEP... - found")
   message(STATUS "Found CLHEP ${CLHEP_VERSION} in ${CLHEP_INCLUDE_DIRS}")
endif()
include_directories(${CLHEP_INCLUDE_DIRS})
# Mark CLHEP_Dir as advanced since can't be set in GUI and this turned out to be confusing
mark_as_advanced(CLHEP_DIR)
