if (USE_AFS AND NOT CLHEP_LIBRARY_DIR)
   if (APPLE)
     set(CLHEP_INCLUDE_DIR /afs/cern.ch/sw/lcg/app/releases/GEANT4/clhep/2.3.1.0/x86_64-mac109-clang35-opt/include)
     set(CLHEP_LIBRARY_DIR /afs/cern.ch/sw/lcg/app/releases/GEANT4/clhep/2.3.1.0/x86_64-mac109-clang35-opt/lib)
   elseif (RHL6)
     set(CLHEP_INCLUDE_DIR /afs/cern.ch/sw/lcg/app/releases/GEANT4/clhep/2.3.4.3/x86_64-slc6-gcc49-opt/include)
     set(CLHEP_LIBRARY_DIR /afs/cern.ch/sw/lcg/app/releases/GEANT4/clhep/2.3.4.3/x86_64-slc6-gcc49-opt/lib)
   endif()
else()
   if($ENV{VERBOSE})
      set(CLHEP_CONFIG_DEBUG TRUE)
   endif()
   find_package(CLHEP REQUIRED)
   message(STATUS "Looking for CLHEP... - found")
   message(STATUS "Found CLHEP ${CLHEP_VERSION} in ${CLHEP_INCLUDE_DIRS}")
endif()
include_directories(${CLHEP_INCLUDE_DIRS})
# Mark CLHEP_Dir as advanced since can't be set in GUI and this turned out to be confusing
mark_as_advanced(CLHEP_DIR)
