# Compiler flags based on build type 
if(${CMAKE_BUILD_TYPE} STREQUAL "Debug")
    add_definitions("-g -O0")
elseif(${CMAKE_BUILD_TYPE} STREQUAL "DebugOutput")
    add_definitions("-g -O0 -DBDSDEBUG")
elseif(${CMAKE_BUILD_TYPE} STREQUAL "DebugCoverage")
    if(NOT CMAKE_COMPILER_IS_GNUCXX)
        message(WARNING "DebugCoverage only works with gcc compiler")
    endif()
    add_definitions("-g -O0 -DBDSDEBUG")
    add_definitions("--coverage")
elseif(${CMAKE_BUILD_TYPE} STREQUAL "None")
    # if specifically None optimise
    set(CMAKE_CXX_FLAGS "-O3 -ffast-math -DNDEBUG")
endif()
