# Check for Scientific Linux
if(UNIX)
    if("${CMAKE_SYSTEM}" MATCHES "el6")
        set(RHL6 TRUE)
    elseif("${CMAKE_SYSTEM}" MATCHES "el7")
        set(RHL7 TRUE)
    endif()
    if(RHL6 OR RHL7)
        set(RHL TRUE)
    endif()
    if("$ENV{HOSTNAME}" MATCHES "lxplus" OR "$ENV{HOSTNAME}" MATCHES "lxfssl")
        set(LXPLUS TRUE)
    else()
        set(LXPLUS FALSE)
    endif()
    if($ENV{VERBOSE})
         message(STATUS "UNIX System Version: ${CMAKE_SYSTEM}")
         message(STATUS "ON HOST: $ENV{HOSTNAME}")
         message(STATUS "ON LXPLUS... - ${LXPLUS}")
    endif()
endif()

# Check for lxplus. We use afs version of Geant4/CLHEP if we are on lxplus by default:
if(EXISTS "/afs/cern.ch" AND LXPLUS)
    option(USE_AFS "Use Geant4/CLHEP libraries from AFS" ON)
    if($ENV{VERBOSE})
         message(STATUS "Use Libraries from LXPLUS")
    endif()
else()
    option(USE_AFS "Use Geant4/CLHEP libraries from AFS" OFF)
endif()

