# Check for Scientific Linux
if(UNIX)
    if("${CMAKE_SYSTEM}" MATCHES "el6")
        set(RHL6 TRUE)
    elseif("${CMAKE_SYSTEM}" MATCHES "el7")
        set(RHL7 TRUE)
    endif()
    if(RHL6 OR RHL7)
        set(RHL TRUE)
    endif()
    if($ENV{VERBOSE})
         message(STATUS "UNIX System Version: ${CMAKE_SYSTEM}")
         message(STATUS "ON HOST: $ENV{HOSTNAME}")
    endif()
endif()
