#include XML directory
find_path(XML2_INCLUDE_DIR NAMES libxml2)
mark_as_advanced(XML2_INCLUDE_DIR)
set(XML_INCLUDE_DIR ${XML2_INCLUDE_DIR}/libxml2)
if($ENV{VERBOSE})
  message(STATUS "XML_INCLUDE_DIR: ${XML_INCLUDE_DIR}")
endif()
find_library(XML_LIBRARIES NAMES xml2 PATH_SUFFIXES xml2)
if(XML_LIBRARIES)
  message(STATUS "Looking for XML2... - found")
  mark_as_advanced(XML_LIBRARIES)
else()
  message(STATUS "Looking for XML2... - Not found")
endif(XML_LIBRARIES)
if($ENV{VERBOSE})
  message(STATUS "XML_LIBRARIES: ${XML_LIBRARIES}")
endif()
